---
title: "Homework"
output: html_notebook
---
```{r}
weather_list <- list(
  c(Thursday <- c(day = "Thursday", temperature = "14 degrees" , chance_of_rain = "56% chance of rain", wind_speed = "10mph")),
  c(Friday <- c(day = "Friday", temperature = "11 degrees", chance_of_rain = "24% chance of rain", wind_speed = "14mph")),
  c(Saturday <- c(day = "Saturday", temperature = "12 degrees", chance_of_rain = "92% chance of rain", wind_speed = "16mph"))
)

```

```{r}
weather_list[[1]][3]
```
```{r}
weather_list[[2]]["wind_speed"]
```

```{r}
weather_list[[1]]["temperature"]
```

```{r}
singing_in_the_rain <- matrix(data = c(
  c(14, 11),
  c(13, 11),
    c(14, 10),
  c(11, 10),
  c(10, 9),
  c(9, 9),
  c(10, 8)
),
  ncol = 7,
  nrow = 2,
byrow = TRUE,
dimnames = list(c("week_01", "week_02"), c("thursday", "friday", "saturday", "sunday", "monday", "tuesday", "wednesday")))

singing_in_the_rain
```

```{r}
singing_in_the_rain[[week_02[3]]]
```


```{r}
singing_in_the_rain[week_02[1:7]]
```
^I'm not sure how I returned these values?

```{r}
singing_in_the_rain["week_01"][]
singing_in_the_rain["week_01"][1]
singing_in_the_rain["week_01"][3]
singing_in_the_rain[week_02][1]
singing_in_the_rain[week_02][3]
singing_in_the_rain[week_02][5]
```

^ I have no idea why it returned that too

```{r}
the_answer <- function(x) {
    answer_x <- if((x) > 10) {
                   print((x)/10)}
       else {print (x)} 
    
      return(paste("The answer is:", answer_x, sep = " "))}
   
```

```{r}
the_answer(9)
```
```{r}
the_answer(15)
```




